const actions = {
    GET_FEED_DATA: 'GET_FEED_DATA',
    SET_HOME_DATA: 'SET_HOME_DATA',
    SET_SUBCATEGORY_DATA: 'SET_SUBCATEGORY_DATA',
    SET_SELECT_ID: 'SET_SELECT_ID',
    RESET_FEED_DATA: 'RESET_FEED_DATA',
} 

export default actions;