const actions = {
  GET_FEED_DATA: 'GET_FEED_DATA',
  SET_HOME_DATA: 'SET_HOME_DATA',
  SET_SUBCATEGORY_DATA: 'SET_SUBCATEGORY_DATA',
  SET_SELECT_ID: 'SET_SELECT_ID',
  RESET_FEED_DATA: 'RESET_FEED_DATA',
  SET_PAUSE_TIME: 'SET_PAUSE_TIME',
  SET_SOUND: 'SET_SOUND',
  SET_USER_DATA: 'SET_USER_DATA',
  BREAK_TIME: 'BREAK_TIME'
};

export default actions;
