const screenNames = {
    HOME: 'HOME',
    ROUTINE: 'ROUTINE',
    EXERCISE: 'EXERCISE',
    SETTINGS: 'SETTINGS',
    HOMESTACK: 'HOMESTACK',
    ROUTINEPLAYLIST: 'ROUTINEPLAYLIST',
    EXERCISE_COMPLETED: 'EXERCISE_COMPLETED'
};

export default screenNames