const screenNames = {
    HOME: 'HOME',
    ROUTINE: 'ROUTINE',
    EXERCISE: 'EXERCISE',
    SETTINGS: 'SETTINGS',
    HOMESTACK: 'HOMESTACK',
    ROUTINEPLAYLIST: 'ROUTINEPLAYLIST',
    EXERCISE_COMPLETED: 'EXERCISE_COMPLETED',
    SPLASH_SCREEN: 'SPLASH_SCREEN',
    USER_CONTAINER: 'USER_CONTAINER'
};

export default screenNames